# Access to the data in this file is provided through EnvConfig - see env_config.rb

defaults: &execution_defaults
  default_config: dev #This just ensures the dev profile (below) is loaded if no CONFIG= is passed from the command line.
  gmail_username: "jenkins@experiencematter.co.uk"
  gmail_password: "!J3nk1n5"
  admin_username: "Matter_Admin"
  admin_password: "=phr*y4~R|;!|WM"
  registered_username: "jenkins@experiencematter.co.uk"
  registered_password: "12345678"
  adviser_username: jenkins+adviser@experiencematter.co.uk
  adviser_password: 12345678
  employer_username: jenkins+employer@experiencematter.co.uk
  employer_password: 12345678

dev:
  <<: *execution_defaults
  base_url: https://dev.nowpensions.com

staging:
  <<: *execution_defaults
  base_url: https://staging.nowpensions.com

live:
  <<: *execution_defaults
  base_url: https://www.nowpensions.com