source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rspec-expectations'
gem 'page-object'
gem 'faker'
gem 'data_magic'
gem 'nokogiri'
gem 'syntax'
gem 'rake'
gem 'activesupport'
gem 'pry', '0.9.12.6'
gem 'rubocop', '0.21.0'